const departamentos = {
"":["-----"],
"Amazonas":["Leticia", "Puerto Nariño", "El Encanto", "La Pedrera", "La Chorrera", "Tarapacá", "Puerto Santander", "Mirití-Paraná", "Puerto Alegría", "Puerto Arica", "La Victoria"],
"Antioquia":["Abriaquí", "Alejandría", "Amagá", "Amalfi", "Andes", "Angelópolis", "Angostura", "Anorí", "Anzá", "Apartadó", "Arboletes", "Armenia", "Barbosa", "Bello", "Belmira", "Betania", "Betulia", "Bolívar", "Briceño", "Buriticá", "Caicedo", "Caldas", "Campamento", "Cañasgordas", "Caracolí", "Caramanta", "Carepa", "Carolina del Príncipe", "Caucasia", "Cisneros", "Concepción", "Concordia", "Copacabana", "Dabeiba", "Donmatías", "Ebéjico", "El Bagre", "El Carmen de Viboral", "El Peñol", "El Retiro", "El Santuario", "Entrerríos", "Envigado", "Fredonia", "Frontino", "Giraldo", "Girardota", "Gómez Plata", "Granada", "Guadalupe", "Guarne", "Guatapé", "Heliconia", "Hispania", "Itagüí", "Ituango", "Jardín", "Jericó", "La Ceja", "La Estrella", "La Pintada", "La Unión", "Liborina", "Maceo", "Marinilla", "Medellín", "Montebello", "Murindó", "Mutatá", "Nariño", "Nechí", "Necoclí", "Peque", "Pueblorrico", "Puerto Berrío", "Puerto Nare", "Puerto Triunfo", "Remedios", "Retiro", "Rionegro", "Sabanalarga", "Sabaneta", "Salgar", "San Andrés de Cuerquia", "San Carlos", "San Francisco", "San Jerónimo", "San José de la Montaña", "San Juan de Urabá", "San Luis", "San Pedro de los Milagros", "San Pedro de Urabá", "San Rafael", "San Roque", "San Vicente", "Santa Bárbara", "Santa Rosa de Osos", "Santo Domingo", "Santuario", "Segovia", "Sonsón", "Sopetrán", "Tarazá", "Tarso", "Támesis", "Titiribí", "Toledo", "Turbo", "Uramita", "Valdivia", "Valparaíso", "Venecia", "Vegachí", "Vigía del Fuerte", "Yalí", "Yarumal", "Yolombó", "Yondó", "Zaragoza"],
"Arauca":["Arauca", "Arauquita", "Cravo Norte", "Fortul", "Puerto Rondón", "Saravena", "Tame"],
"Atlántico": ["Barranquilla", "Baranoa", "Candelaria", "Campo de la Cruz", "Galapa", "Juan de Acosta", "Luruaco", "Malambo", "Manatí", "Palmar de Varela", "Piojó", "Ponedera", "Polonuevo", "Puerto Colombia", "Repelón", "Sabanagrande", "Sabanalarga", "Santa Lucía", "Soledad", "Suán", "Santo Tomás", "Tubará", "Usiacurí"],
"Bolívar": ["Achí", "Altos del Rosario", "Arjona", "Arroyohondo", "Arenal", "Barranco de Loba", "Brazuelo de Papayal", "Cantagallo", "Clemencia", "Córdoba", "Calamar", "Cicuco", "El Carmen de Bolívar", "El Guamo", "El Peñón", "Hatillo de Loba", "Magangué", "Mahates", "María La Baja", "Margarita", "Mompox", "Morales", "Montecristo", "Norosí", "Pinillos", "Regidor", "Río Viejo", "Sabana Grande", "San Cristóbal", "San Estanislao", "San Jacinto", "San Jacinto del Cauca", "San Juan Nepomuceno", "San Martín de Loba", "San Pablo", "Santa Catalina", "Santa Cruz de Mompox", "Santa Rosa", "Santa Rosa del Sur", "Simití", "Soplaviento", "Suán", "Talaigua Nuevo", "Tiquisio", "Tubará", "Turbaco", "Turbaná", "Villanueva", "Zambrano"],
"Boyacá": ["Aquitania", "Arcabuco", "Belén", "Berbeo", "Betéitiva", "Boavita", "Boyacá", "Briceño", "Buenavista", "Busbanzá", "Caldas", "Campohermoso", "Cerinza", "Chita", "Chitaraque", "Chivatá", "Chivor", "Chiquinquirá", "Chiscas", "Chitagá", "Chivatá", "Chíquiza", "Chívor", "Ciénega", "Coper", "Corrales", "Covarachía", "Cubará", "Cubará", "Cucaita", "Cuítiva", "Cómbita", "Duitama", "El Cocuy", "El Espino", "Firavitoba", "Floresta", "Gachantivá", "Gameza", "Garagoa", "Guacamayas", "Guateque", "Guayatá", "Güicán", "Iza", "Jenesano", "La Capilla", "La Uvita", "Labranzagrande", "Macanal", "Maripí", "Miraflores", "Mongua", "Monguí", "Moniquirá", "Motavita", "Muzo", "Nobsa", "Nuevo Colón", "Oicatá", "Otanche", "Pachavita", "Pajarito", "Paz del Río", "Pauna", "Payá", "Paipa", "Paz de Río", "Pesca", "Pisba", "Puerto Boyacá", "Quípama", "Ráquira", "Ramiriquí", "Rondón", "Saboyá", "Sachicá", "Samacá", "San Eduardo", "San José de Pare", "San Luis de Gaceno", "San Mateo", "San Miguel de Sema", "San Pablo de Borbur", "Santa María", "Santa Rosa de Viterbo", "Santana", "Sativasur", "Sativanorte", "Siachoque", "Soatá", "Socha", "Socotá", "Sogamoso", "Somondoco", "Sora", "Soracá", "Sotaquirá", "Sutamarchán", "Sutatenza", "Susacón", "Tasco", "Tasco", "Tasco", "Tenza", "Tibaná", "Tinjacá", "Tipacoque", "Toca", "Togüí", "Tota", "Tota", "Tutazá", "Tuta", "Turmequé", "Tutazá", "Tópaga", "Ventaquemada", "Villa de Leyva", "Viracachá", "Zetaquira"],
"Caldas": ["Anserma", "Aguadas", "Aranzazu", "Belalcázar", "Chinchiná", "Filadelfia", "La Dorada", "La Merced", "Manizales", "Manzanares", "Marquetalia", "Marmato", "Marulanda", "Neira", "Norcasia", "Pácora", "Palestina", "Pensilvania", "Riosucio", "Risaralda", "Salamina", "Samaná", "San José", "Supía", "Villamaría", "Viterbo"],
"Caquetá": ["Albania", "Belén de los Andaquíes", "Cartagena del Chairá", "Curillo", "El Doncello", "El Paujil", "Florencia", "La Montañita", "Morelia", "Puerto Milán", "Puerto Rico", "San José del Fragua", "San Vicente del Caguán", "Solano", "Solita", "Valparaíso"],
"Casanare": ["Aguaazul", "Hato Corozal", "La Salina", "Maní", "Monterrey", "Nunchía", "Orocué", "Paz de Ariporo", "Pore", "Recetor", "Sabanalarga", "San Luis de Palenque", "Támara", "Tauramena", "Trinidad", "Villanueva", "Yopal"],
"Cauca": ["Almaguer", "Argelia", "Balboa", "Bolívar", "Buenos Aires", "Cajibío", "Caldonó", "Caloto", "Corinto", "El Tambo", "Florencia", "Guachené", "Guapi", "Hato Corozal", "Inzá", "Jambaló", "La Sierra", "La Vega", "López de Micay", "Maní", "Mercaderes", "Miranda", "Mora", "Padilla", "Patía", "Paz de Ariporo", "Piamonte", "Piendamó", "Popayán", "Puerto Milán", "Puerto Rico", "Puerto Tejada", "Puracé", "Recetor", "Riosucio", "Rosas", "Sabalarga", "San José del Fragua", "San Luis de Palenque", "San Sebastián", "Santa Rosa", "Santander de Quilichao", "Silvia", "Solano", "Suárez", "Sotará", "Sucre", "Támara", "Timbiquí", "Timbío", "Totoró", "Toribío", "Valparaíso", "Villa Rica", "Villamaría", "Villanueva", "Yopal"],
"Cesar": ["Aguachica", "Astrea", "Becerril", "Bosconia", "Chimichagua", "Chiriguaná", "Codazzi", "Curumaní", "El Copey", "El Paso", "Gamarra", "González", "La Gloria", "La Jagua de Ibirico", "La Paz", "Manaure Balcón del Cesar", "Pailitas", "Pelaya", "Pueblo Bello", "Río de Oro", "San Alberto", "San Diego", "San Martín", "Tamalameque", "Valledupar"],
"Chocó": ["Acandí", "Alto Baudó", "Atrato", "Bagadó", "Bahía Solano", "Bajo Baudó", "Bojayá", "Cantón de San Pablo", "Cértegui", "Condoto", "El Carmen de Atrato", "El Carmen del Darién", "El Copey", "Istmina", "Juradó", "Litoral de San Juan", "Lloró", "Medio Atrato", "Medio Baudó", "Medio San Juan", "Nóvita", "Nuquí", "Quibdó", "Río Iró", "Río Quito", "Riosucio", "San José del Palmar", "Tadó", "Unión Panamericana", "Unguía"],
"Córdoba": ["Ayapel", "Buenavista", "Canalete", "Cereté", "Chimá", "Chinú", "Cotorra", "Ciénaga de Oro", "La Apartada", "Los Córdobas", "Momil", "Monelíbano", "Montería", "Moñitos", "Planeta Rica", "Pueblo Nuevo", "Purísima", "Puerto Escondido", "Puerto Libertador", "Puerto Sánchez", "Purísima", "Sahagún", "San Andrés de Sotavento", "San Antero", "San Bernardo del Viento", "San Carlos", "San José de Uré", "San Pelayo", "Santa Cruz de Lorica", "Tierralta", "Tuchín", "Valencia"],
"Cundinamarca": ["Agua de Dios", "Albán", "Anapoima", "Anolaima", "Apulo", "Arbeláez", "Beltrán", "Bituima", "Bojacá", "Bogotá", "Cabrera", "Cachipay", "Cajicá", "Caqueza", "Caparrapí", "Carmen de Carupa", "Chaguaní", "Chía", "Chipaque", "Choachí", "Chocontá", "Cogua", "Cota", "Cucunubá", "El Colegio", "El Peñón", "El Rosal", "Fómeque", "Fosca", "Funza", "Fúquene", "Gachalá", "Gachancipá", "Gachetá", "Gama", "Girardot", "Granada", "Guachetá", "Guaduas", "Guasca", "Guataquí", "Guatavita", "Guayabal de Síquima", "Guayabetal", "Gutierrez", "Jerusalén", "Junín", "La Calera", "La Mesa", "La Palma", "La Peña", "La Vega", "Lenguazaque", "Machetá", "Madrid", "Manta", "Medina", "Mosquera", "Nariño", "Nemocón", "Nilo", "Nimaima", "Nocaima", "Pacho", "Pandi", "Paime", "Paratebueno", "Pasca", "Pulí", "Quebradanegra", "Quetame", "Quipile", "Ricaurte", "San Antonio del Tequendama", "San Bernardo", "San Cayetano", "San Francisco", "San Juan de Rioseco", "Sasaima", "Sesquilé", "Sibaté", "Silvania", "Simijaca", "Soacha", "Sopó", "Subachoque", "Supatá", "Susa", "Suesca", "Sutatausa", "Tabio", "Tausa", "Tena", "Tenjo", "Tibirita", "Tocaima", "Tocancipá", "Topaipí", "Ubala", "Ubaté", "Une", "Urica", "Utica", "Venecia", "Vergara", "Vianí", "Villeta", "Villagómez", "Viotá", "Zipacón", "Zipaquirá"],
"Guainía": ["Barranco Minas", "Cacahual", "Inírida", "La Guadalupe", "Mapiripana", "Moricual Nuevo", "Pana Pana", "Puerto Colombia", "San Felipe"],
"Guaviare": ["Calamar", "El Retorno", "Miraflores", "San José del Guaviare"],
"Huila": ["Agrado", "Aipe", "Algeciras", "Altamira", "Baraya", "Camposalegre", "Colombia", "Elías", "Guadalupe", "Hobo", "Íquira", "Isnos", "La Argentina", "La Plata", "Municipio de Colombia", "Nátaga", "Neiva", "Oporapa", "Palestina", "Pital", "Pitalito", "Rivera", "Saladoblanco", "San Agustín", "Santa María", "Suaza", "Tarqui", "Tello", "Teruel", "Tesalia", "Timaná", "Villavieja", "Yaguará"],
"La Guajira": ["Albania", "Barrancas", "Dibulla", "Distracción", "El Molino", "Fonseca", "Hatonuevo", "La Jagua del Pilar", "Maicao", "Manaure", "Riohacha", "San Juan del Cesar", "Uribia", "Urumita", "Villanueva"],
"Magdalena": ["Algarrobo", "Aracataca", "Ariguani", "Cerro de San Antonio", "Chibolo", "Ciénaga", "Concordia", "El Banco", "El Piñón", "El Retén", "Fundación", "Guamal", "Maicao", "Nueva Granada", "Pijiño del Carmen", "Pivijay", "Pueblo Viejo", "Plato", "Remolino", "Sabanas de San Angel", "Salamina", "San Sebastián de Buenavista", "San Zenón", "Santa Ana", "Santa Bárbara de Pinto", "Santa Marta", "Sitionuevo", "Tenerife", "Uribia", "Zapayán", "Zona Bananera"],
"Meta": ["Acacías", "Barranca de Upía", "Cabuyaro", "Castilla La Nueva", "Cubarral", "Cumaral", "El Calvario", "El Castillo", "El Dorado", "Fuente de Oro", "Granada", "Guamal", "La Macarena", "La Uribe", "Lejanías", "Mesetas", "Mapiripán", "Measetas", "Puerto Concordia", "Puerto Gaitán", "Puerto Lleras", "Puerto López", "Puerto Rico", "Restrepo", "San Carlos de Guaroa", "San Juan de Arama", "San Juanito", "San Martín", "Uribia", "Villavicencio", "Vista Hermosa"],
"Nariño": ["Albán", "Aldana", "Ancuyá", "Arboleda", "Barbacoas", "Belén", "Buesaco", "Córdoba", "Chachagüí", "Colón", "Contadero", "Cumbal", "Cumbitara", "Cuaspud", "El Charco", "El Peñol", "El Rosario", "El Tablón de Gómez", "El Tambo", "Funes", "Francisco Pizarro", "Funza", "Gualmatán", "Guaitarilla", "Guachucal", "Iles", "Imués", "Ipiales", "La Cruz", "La Florida", "La Llanada", "La Tola", "Linares", "Los Andes", "Magüí Payán", "Mallama", "Nariño", "Olaya Herrera", "Ospina", "Policarpa", "Potosí", "Puerres", "Pupiales", "Providencia", "Ricaurte", "Roberto Payán", "San Bernardo", "San José de Albán", "San Juan de Pasto", "San Lorenzo", "San Martín", "San Pablo", "San Pedro de Cartago", "San Juan de Pasto", "San Juanito", "Samaniego", "Santa Bárbara", "Santacruz", "Sandoná", "Santa Bárbara", "Taminango", "Tangua", "Túquerres", "Tumaco", "Túquerres", "Yacuanquer"],
"Norte de Santander": ["Abrego", "Arboledas", "Bochalema", "Bucarasica", "Cácota", "Cáchira", "Chitagá", "Chitaga", "Chinácota", "Convención", "Cucuta", "Cucutilla", "Duranía", "El Carmen", "El Tarra", "El Zulia", "Gramalote", "Hacarí", "Herrán", "Labateca", "La Esperanza", "La Playa de Belén", "Lourdes", "Los Patios", "Mutiscua", "Ocaña", "Pamplona", "Pamplonita", "Puerto Santander", "Ragonvalia", "Salazar de Las Palmas", "San Calixto", "San Cayetano", "San Domingo de Silos", "Santiago", "Santo Domingo de Silos", "Sardinata", "Teorama", "Tibú", "Toledo", "Villa Caro", "Villa del Rosario"],
"Putumayo": ["Colón", "Mocoa", "Orito", "Puerto Asís", "Puerto Caicedo", "Puerto Guzmán", "Puerto Leguizamo", "Santiago", "San Francisco", "San Miguel", "Sibundoy", "Valle del Guamuez", "Villagarzón"],
"Quindío": ["Armenia", "Buenavista", "Calarcá", "Circasia", "Córdoba", "Filandia", "Génova", "La Tebaida", "Montenegro", "Pijao", "Quimbaya", "Salento"],
"Risaralda": ["Apía", "Balboa", "Belén de Umbría", "Dosquebradas", "Guática", "La Celia", "La Virginia", "Marsella", "Mistrató", "Pereira", "Pueblo Rico", "Quinchía", "Santa Rosa de Cabal", "Santuario"],
"San Andrés y Providencia": ["Cayos", "Providencia", "San Andrés", "Santa Catalina"],
"Santander": ["Albania", "Aguada", "Aratoca", "Barbosa", "Barrancabermeja", "Betulia", "Bolívar", "Bucaramanga", "Cabrera", "Carcasí", "Cerrito", "Charalá", "Charta", "Chima", "Chipatá", "Cimitarra", "Concepción", "Confines", "Contratación", "Coromoro", "Curití", "El Carmen de Chucurí", "El Guacamayo", "El Peñón", "Encino", "Enciso", "Floridablanca", "Florián", "Galán", "Gámbita", "Guaca", "Guadalupe", "Guapotá", "Güepsa", "Hato", "Jesús María", "Jordán", "La Belleza", "La Paz", "Landázuri", "Lebrija", "Los Santos", "Macaravita", "Málaga", "Matanza", "Mogotes", "Molagavita", "Oiba", "Onzaga", "Palmar", "Palmas del Socorro", "Pinchote", "Páramo", "Puente Nacional", "Puerto Parra", "Puerto Wilches", "Rionegro", "Sabana de Torres", "San Andrés", "San Benito", "San Gil", "San Joaquín", "San Juan de Girón", "San Miguel", "San Vicente de Chucurí", "Santa Bárbara", "Santa Helena del Opón", "Santa Rosa de Cabal", "Socorro", "Suaita", "Sucre", "Suratá", "Tona", "Valle de San José", "Vetas", "Vélez", "Villanueva", "Zapatoca"],
"Sucre": ["Buena Vista", "Caimito", "Chalán", "Colosó", "Corozal", "Coveñas", "El Roble", "Galeras", "Guaranda", "La Unión", "Los Palmitos", "Majagual", "Morroa", "Ovejas", "Palmito", "Sampués", "San Benito Abad", "San Juan de Betulia", "San Marcos", "San Onofre", "San Pedro", "Santa María", "Santiago de Tolú", "Sincelejo", "Sincé", "Sucre", "Tolú Viejo"],
"Tolima": ["Alpujarra", "Alvarado", "Ambalema", "Anzoátegui", "Armero", "Ataco", "Cajamarca", "Casabianca", "Chaparral", "Coello", "Cunday", "Dolores", "Espinal", "Falán", "Flandes", "Fresno", "Guamo", "Herveo", "Honda", "Icononzo", "Ibagué", "Lérida", "Líbano", "Mariquita", "Melgar", "Murillo", "Natagaima", "Ortega", "Palocabildo", "Piedras", "Planadas", "Prado", "Purificación", "Rioblanco", "Roncesvalles", "Rovira", "Saldaña", "San Antonio", "San Luis", "Santa Isabel", "Suárez", "Valle de San Juan", "Villahermosa", "Villarrica"],
"Valle del Cauca": ["Alcalá", "Andalucía", "Ansermanuevo", "Argelia", "Bolívar", "Bugalagrande", "Buga", "Buenaventura", "Cali", "Caicedonia", "Candelaria", "Cartago", "Dagua", "Darién", "El Águila", "El Cairo", "El Cerrito", "El Dovio", "Floridablanca", "Florida", "Ginebra", "Guacarí", "Guamo", "Jamundí", "La Cumbre", "La Unión", "La Victoria", "Obando", "Palmira", "Pradera", "Restrepo", "Ríofrío", "Roldanillo", "San Pedro", "Sevilla", "Toro", "Tuluá", "Trujillo", "Ullóa", "Versalles", "Vijes", "Yotoco", "Yumbo", "Zarzal"],
"Vaupés": ["Carurú", "Mitú", "Pacoa", "Papunaua", "Taraira", "Yavaraté"],
"Vichada": ["Cumaribo", "La Primavera", "Puerto Carreño", "Santa Rosalía"],
    // Agrega más departamentos y ciudades según sea necesario
};


function cargarCiudades() {
    const departamentoSelect = document.getElementById('departamento');
    const ciudadSelect = document.getElementById('municipio');
    const municipioGuardado = ciudadSelect.getAttribute('data-municipio');

    // Limpiar la lista de ciudades
    ciudadSelect.innerHTML = '';

    // Obtener las ciudades del departamento seleccionado
    const departamentoSeleccionado = departamentoSelect.value;
    const ciudades = departamentos[departamentoSeleccionado] || [];

    // Llenar la lista de ciudades y seleccionar la guardada si coincide
    ciudades.forEach((ciudad) => {
        const option = document.createElement('option');
        option.value = ciudad;
        option.textContent = ciudad;
        if (ciudad === municipioGuardado) {
            option.selected = true; // Seleccionar el municipio guardado
        }
        ciudadSelect.appendChild(option);
    });
}

// Llamar a cargarCiudades al cargar la página y al cambiar el departamento
document.addEventListener('DOMContentLoaded', function () {
    cargarCiudades();
    document.getElementById('departamento').addEventListener('change', cargarCiudades);
});